/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IDODOV2Interface extends utils.Interface {
  functions: {
    "querySellBase(address,uint256)": FunctionFragment;
    "querySellQuote(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "querySellBase" | "querySellQuote"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "querySellBase",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "querySellQuote",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "querySellBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "querySellQuote",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDODOV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDODOV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    querySellBase(
      trader: PromiseOrValue<string>,
      payBaseAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveQuoteAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;

    querySellQuote(
      trader: PromiseOrValue<string>,
      payQuoteAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveBaseAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;
  };

  querySellBase(
    trader: PromiseOrValue<string>,
    payBaseAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { receiveQuoteAmount: BigNumber; mtFee: BigNumber }
  >;

  querySellQuote(
    trader: PromiseOrValue<string>,
    payQuoteAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { receiveBaseAmount: BigNumber; mtFee: BigNumber }
  >;

  callStatic: {
    querySellBase(
      trader: PromiseOrValue<string>,
      payBaseAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveQuoteAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;

    querySellQuote(
      trader: PromiseOrValue<string>,
      payQuoteAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveBaseAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    querySellBase(
      trader: PromiseOrValue<string>,
      payBaseAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    querySellQuote(
      trader: PromiseOrValue<string>,
      payQuoteAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    querySellBase(
      trader: PromiseOrValue<string>,
      payBaseAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    querySellQuote(
      trader: PromiseOrValue<string>,
      payQuoteAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
