/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IDODOProxyInterface extends utils.Interface {
  functions: {
    "dodoSwapV1(address,address,uint256,uint256,address[],uint256,bool,uint256)": FunctionFragment;
    "dodoSwapV2TokenToToken(address,address,uint256,uint256,address[],uint256,bool,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "dodoSwapV1" | "dodoSwapV2TokenToToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dodoSwapV1",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dodoSwapV2TokenToToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "dodoSwapV1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dodoSwapV2TokenToToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDODOProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDODOProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dodoSwapV1(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      arg6: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    dodoSwapV2TokenToToken(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      isIncentive: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  dodoSwapV1(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    fromTokenAmount: PromiseOrValue<BigNumberish>,
    minReturnAmount: PromiseOrValue<BigNumberish>,
    dodoPairs: PromiseOrValue<string>[],
    directions: PromiseOrValue<BigNumberish>,
    arg6: PromiseOrValue<boolean>,
    deadLine: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  dodoSwapV2TokenToToken(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    fromTokenAmount: PromiseOrValue<BigNumberish>,
    minReturnAmount: PromiseOrValue<BigNumberish>,
    dodoPairs: PromiseOrValue<string>[],
    directions: PromiseOrValue<BigNumberish>,
    isIncentive: PromiseOrValue<boolean>,
    deadLine: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    dodoSwapV1(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      arg6: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dodoSwapV2TokenToToken(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      isIncentive: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    dodoSwapV1(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      arg6: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    dodoSwapV2TokenToToken(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      isIncentive: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    dodoSwapV1(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      arg6: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    dodoSwapV2TokenToToken(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromTokenAmount: PromiseOrValue<BigNumberish>,
      minReturnAmount: PromiseOrValue<BigNumberish>,
      dodoPairs: PromiseOrValue<string>[],
      directions: PromiseOrValue<BigNumberish>,
      isIncentive: PromiseOrValue<boolean>,
      deadLine: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
